name: Build and Test workflow
on:
  workflow_call:

jobs:
  build_and_test:
    strategy:
      matrix:
        node-version: ['20.15.1']
        os: ['macos-latest', 'windows-latest']
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout and Install Dependencies
        uses: ./.github/actions/project-setup
        with:
          node-version: ${{matrix.node-version}}
      - name: Build the project files
        run: npm run build
      - name: Generate Test coverage report
        run: npm run coverage
      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-coverage-report
          path: coverage/
