name: Delete cache
on:
  pull_request_target:
    types:
      - closed

jobs:
  delete_npm_cache:
    strategy:
      matrix:
        node-version: ['20.15.1']
        os: ['macos-latest', 'windows-latest']
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ${{matrix.os}}
    permissions:
      actions: write # Grant write access to actions
      contents: read # Default permission for repository contents
    steps:
      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > ~/.gh_token
          gh auth login --with-token < ~/.gh_token
      - name: Cleanup
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
