name: Delete cache
on:
  pull_request_target:
    types:
      - closed

jobs:
  delete_npm_cache:
    strategy:
      matrix:
        node-version: ['20.15.1']
        os: ['macos-latest', 'windows-latest']
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ${{matrix.os}}
    steps:
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log npm Cache Directory
        run: |
          echo "npm cache directory:"
          echo $(npm config get cache)
      - name: Clear npm Cache
        run: npm cache clean --force
      - name: Confirm Cache Directory
        run: |
          echo "Remaining npm cache directory:"
          ls -la $(npm config get cache) || echo "Cache cleared successfully!"
